export const amenities = [
	{ id: "airCondition", label: "Air conditioning", parent: "componentsDto" },
	{ id: "courtyard", label: "Courtyard", parent: "componentsDto" },
	{ id: "furniture", label: "Furniture", parent: "componentsDto" },
	{ id: "gasStove", label: "Gas Stove", parent: "componentsDto" },
	{ id: "internet", label: "Internet", parent: "componentsDto" },
	{ id: "tv", label: "TV", parent: "componentsDto" },
	{ id: "busStop", label: "Bus Stop", parent: "homeAmenitiesDto" },
	{ id: "garden", label: "Garden", parent: "homeAmenitiesDto" },
	{ id: "market", label: "Market", parent: "homeAmenitiesDto" },
	{ id: "park", label: "Park", parent: "homeAmenitiesDto" },
	{ id: "parking", label: "Parking", parent: "homeAmenitiesDto" },
	{ id: "school", label: "School", parent: "homeAmenitiesDto" },
	{ id: "stadium", label: "Stadium", parent: "homeAmenitiesDto" },
	{ id: "subway", label: "Subway", parent: "homeAmenitiesDto" },
	{ id: "superMarket", label: "Super Market", parent: "homeAmenitiesDto" },
];
