import product_1 from "../../assets/img/product_1.jpg";
import product_2 from "../../assets/img/product_2.jpg";
import ava_1 from "../../assets/img/ava_1.jpg";
import ava_2 from "../../assets/img/ava_2.png";
import ava_3 from "../../assets/img/ava_3.png";

export const recommended = [
	{
		id: 1,
		image: product_1,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "7,500",
		sale: "2,800",
	},
	{
		id: 2,
		image: product_2,
		ava: ava_2,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "4,000",
		sale: "1,800",
	},
	{
		id: 3,
		image: product_1,
		ava: ava_3,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "10,000",
		sale: "5,800",
	},
	{
		id: 45,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
	{
		id: 46,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
	{
		id: 47,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
	{
		id: 48,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
	{
		id: 49,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
	{
		id: 41,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
	{
		id: 42,
		image: product_2,
		ava: ava_1,
		title: "New Apartment Nice Wiew",
		address: "Quincy St, Brooklyn, NY, USA",
		houseDetails: {
			garage: 3,
			bath: 2,
			rooms: 10,
			beds: 2,
		},
		price: "1,500",
		sale: "800",
	},
];
